image: alpine/latest
packages:
  - go
  # Required by codecov
  - bash
  - findutils
sources:
  - https://github.com/uponusolutions/go-sasl
tasks:
  - build: |
      cd go-sasl
      go build -v ./...
  - test: |
      cd go-sasl
      go test -coverprofile=coverage.txt -covermode=atomic ./...
